from main_countlignes import *
from main_demineur import *
from main_terminalFunctions import *
from main_gamemakerterminal import *
from main_customElement import *
from main_terminalGetKey import *
from main_duplicateFile import *
from main_messy import *
if sys.version[0:4] != "3.10":
    from main_minesweeper import *
    from main_tetris import *
